# Generated by Django 4.2.2 on 2023-06-19 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='publisher',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
